site_name: TAssistant docs
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Русский
      link: /ru/
      lang: ru


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
